baseurl = "http://personalizationpodcast.com/"
languageCode = "en-us"
title = "The Personalization Podcast"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "personalizationpodcast"
theme = "hugo-minimalist-theme"

[params]
    site_author = "Dave Ingram"
    site_description = "All About Personalized Experiences."
    location = "Boston, MA"
    # All paths are relative to the baseurl. Put your files
    # somewhere in the static folder.
    avatar = "images/dave-profile.jpg"
    header_background = "img/desk.jpg"
    header_title = "Personalization Podcast"
    copyright = "Copyright 2016 - [Dave Ingram](daveingram.us)."

    # Enable gogle analytics by entering your tracking code
    google_analytics = "UA-71857986-1"

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "p13npodcast"
    facebook  = "PersonalizationPodcast"
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = ""
    gplus     = ""
