#!/bin/bash

hugo
git add .
git commit -m"$1"
git push origin master
rsync -rv ./ ../personalizationpodcast.github.io/
cd personalizationpodcast.github.io
git add .
git commit -m"$1"
git push origin master
cd -
